### PR TITLE
Feat: add a metadata template

### PR DESCRIPTION
**Pull request by cristianvasquez**
This adds a metadata example to the pipeline template (to be filled in)

https://github.com/zazuko/xrm-xml-workflow/issues/4

### CODE REVIEW

**Comment by tpluscode** [comment]
IMO we don't really understand the requirements for a practical solution and it's too early to add this already to the example workflow

**Comment by cristianvasquez** [comment]
This is not the prov Metadata step but the 'normal' Metadata, for templates

**Comment by cristianvasquez** [comment]
However, after second thought, we could arrive at much more generic mechanisms for RDF metadata templates that attach to entities.

Related: https://github.com/zazuko/barnard59/issues/135

Some POCs: https://github.com/zazuko/barnard59-examples-pocs/tree/main/examples

I'll move this to draft

**Comment by tpluscode** [comment]
> However, after second thought, we could arrive at much more generic mechanisms for RDF metadata templates that attach to entities.

Indeed, I was thinking that cube-creator could also take advantage of such a step to provide its metadata instead of the current solution. And then also from other sources such as CI variables or model metadata (WIP with @magdasalatka)

**Comment by tpluscode** [comment]
Closed in favor of https://github.com/zazuko/barnard59/issues/92

**Pull request closed without merging**
